name: Java-app-cicd

on:
  push:
    branches:
    - main

jobs:
  my_job_1:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4


    - name: Install Java and Maven
      uses: actions/setup-java@v4
      with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
    - name: Build the Project
      run: mvn clean package

    - name: check workspace
      run: |
        echo ${{ github.workspace }}
        ls -lrth

    - name: Upload target folder
      uses: actions/upload-artifact@v4
      with:
        name: hello-world
        path: |
          ${{ github.workspace }}/**/*.war


  my_job_2:
    runs-on: ubuntu-22.04

    steps:
    - name: dowload artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-world
        path: target    