name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn clean install -f pom.xml
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=hello-project 
          -Dsonar.host.url=http://13.57.25.121:9000 
          -Dsonar.login=sqp_f7346d32fe5e435a735899773d765f258619e743
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # - name: sonar scan
    #   run: |
    #     mvn clean verify sonar:sonar \
    #     -Dsonar.projectKey=hello-project \
    #     -Dsonar.host.url=http://13.57.25.121:9000 \
    #     -Dsonar.login=sqp_f7346d32fe5e435a735899773d765f258619e743