name: Java-app-cicd

run-name: ${{ github.actor }} is building java applications

on:
  # push:
  #   branches:
  #   - main
  workflow_dispatch:

jobs:
  my_job_1:
    runs-on: ubuntu-22.04
    
    # if: always()
    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4


    - name: Install Java and Maven
      uses: actions/setup-java@v4
      with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
    - name: Build the Project
      run: mvn clean package

    - name: check workspace
      run: |
        echo ${{ github.workspace }}
        ls -lrth

    - name: Upload target folder
      uses: actions/upload-artifact@v4
      with:
        name: hello-world
        path: |
          ${{ github.workspace }}/**/*.war


  my_job_2:
    needs: my_job_1
    runs-on: ubuntu-22.04

    steps:
    - name: dowload artifact
      uses: actions/download-artifact@v4
      # with:
      #   name: hello-world
      #   path: ${{ github.workspace }}/**/*.war   
  
  my_job_3:
    runs-on: ubuntu-22.04
    needs: [ my_job_1, my_job_2]

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4

    - name: dowload artifact
      uses: actions/download-artifact@v4

    - name: check workspace
      run: |
        echo ${{ github.workspace }}
        ls -lrth


    - name: deploy application
      run: docker image build -t my-app .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: docker image tag 
      run: docker image tag my-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

    - name: docker image push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
