name: Java app CI/CD

run-name: ${{ github.actor }} is building java applications

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: shashikamle99
  DOCKER_IMAGE: java-hello-app

jobs:
  build_package:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4

    - name: select specific java package
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: check version java and maven
      run: |
        java -version 
        mvn --version

    - name: build java package
      run: mvn clean package

    - name: check artifact
      run: ls -la  ${{ github.workspace }}/target

# Upload artifacts
    
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: ${{ github.workspace }}/target/*.war

  
  build_docker_image:
    runs-on: ubuntu-22.04
    needs: build_package

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4

    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: java-app
        path: target

    - name: check artifact in workspace
      run: ls -la  ${{ github.workspace }}/target    
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build image
      run: docker image build -t '${{ env.DOCKERHUB_USERNAME }}/${{ DOCKER_IMAGE }}:latest' .

    # - name: push image
    #   run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ DOCKER_IMAGE }}:latest  


      