name: Java app CI/CD

run-name: ${{ github.actor }} is building java applications

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: shashikamle99
  DOCKER_IMAGE: java-app

jobs:
  build_package:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4

    - name: select specific java package
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: check version java and maven
      run: |
        java -version 
        mvn --version

    - name: build java package
      run: mvn clean package

    - name: check artifact
      run: ls -la  ${{ github.workspace }}/target

    # - name: SonarQube Scan
    #   uses: sonarsource/sonarqube-scan-action@master
    #   with:
    #     projectBaseDir: .
    #     args: >
    #       -Dsonar.organization=java_project
    #       -Dsonar.projectKey=java_project
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=java_project -Dsonar.projectName='java_project'

      