name: Java app CI/CD

run-name: ${{ github.actor }} is building java applications

on:
  push:
    branches:
      - main
  workflow_disptach:   


jobs:
  build_job:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4

    - name: check the workspace
      run: |
        echo ${{ github.workspace }}
        ls -la  ${{ github.workspace }}


